version: "3.7"

services:
  ws-scraper-live:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: ws-scraper-live
    environment:
      - SWITCH=live
    network_mode: host
    volumes:
      - ./logs:/logs
      - ./raw_missing:/raw_missing

  ws-scraper-sender:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: ws-scraper-sender
    environment:
      - SWITCH=sender
    network_mode: host
    volumes:
      - ./logs:/logs

  redis-scraper:
    image: redis:latest
    container_name: redis-container
    restart: unless-stopped
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - redis_data:/data

volumes:
  redis_data:
    driver: local
